import type { MigrationPlan, NotionSnapshot } from '../db/import/notion/types';

/*
 * A small, made-up Notion workspace for the importer tests. Generic on
 * purpose: nothing here comes from anyone's real workspace.
 */

export const ID = {
  hq: 'a0000000000000000000000000000001',
  plan: 'a0000000000000000000000000000002',
  spec: 'a0000000000000000000000000000003',
  graveyard: 'a0000000000000000000000000000004',
  oldIdea: 'a0000000000000000000000000000005',
  projectsDb: 'b0000000000000000000000000000001',
  tasksDb: 'b0000000000000000000000000000002',
  phaseTasksDb: 'b0000000000000000000000000000003',
  eventsDb: 'b0000000000000000000000000000004',
  decisionsDb: 'b0000000000000000000000000000005',
  colorsDb: 'b0000000000000000000000000000006',
  viewOfTasks: 'b0000000000000000000000000000007',
  rowWidget: 'c0000000000000000000000000000001',
  rowWidgetOld: 'c0000000000000000000000000000002',
  rowGadget: 'c0000000000000000000000000000003',
  taskShip: 'd0000000000000000000000000000001',
  taskDraft: 'd0000000000000000000000000000002',
  taskBlank: 'd0000000000000000000000000000003',
  phaseTaskDraft: 'd0000000000000000000000000000004',
  phaseTaskLaunch: 'd0000000000000000000000000000005',
  eventJam: 'e0000000000000000000000000000001',
  eventCup: 'e0000000000000000000000000000002',
  decisionOne: 'f0000000000000000000000000000001',
  decisionTwo: 'f0000000000000000000000000000002',
  colorRed: '10000000000000000000000000000001',
  colorBlue: '10000000000000000000000000000002',
} as const;

const url = (id: string) => `https://app.notion.com/p/${id}`;
const rowPage = (id: string, parentId: string, title: string, body = '') => ({
  id,
  url: url(id),
  title,
  parentId,
  parentKind: 'database' as const,
  body,
  lastEditedAt: '2026-01-02T10:00:00.000Z',
});

export function fixtureSnapshot(): NotionSnapshot {
  return {
    capturedAt: '2026-01-05T00:00:00.000Z',
    pages: [
      {
        id: ID.hq,
        url: url(ID.hq),
        title: 'Acme HQ',
        icon: '🏢',
        parentId: null,
        parentKind: null,
        lastEditedAt: '2026-01-03T09:00:00.000Z',
        body: [
          'Home of the Widget work.',
          `<page url="${url(ID.spec)}">Widget Spec</page>`,
          `<page url="${url(ID.plan)}">Widget Plan</page>`,
          `<database url="${url(ID.projectsDb)}" inline="false">Projects</database>`,
          `<database url="${url(ID.tasksDb)}" inline="false">Tasks</database>`,
          `<database url="${url(ID.viewOfTasks)}" inline="true"></database>`,
          `<page url="${url(ID.graveyard)}">Graveyard</page>`,
        ].join('\n'),
      },
      {
        id: ID.plan,
        url: url(ID.plan),
        title: 'Widget Plan',
        parentId: ID.hq,
        parentKind: 'page',
        body: [
          '# Plan',
          `See <mention-page url="${url(ID.spec)}"/> and <mention-page url="${url('9'.repeat(32))}">Elsewhere</mention-page>.`,
          '<file src="https://files.example.com/signed/brief.pdf?sig=1">Brief</file>',
          '<empty-block/>',
          'Costs \\$5 and \\~2 days.',
        ].join('\n'),
      },
      {
        id: ID.spec,
        url: url(ID.spec),
        title: 'Widget Spec',
        parentId: ID.hq,
        parentKind: 'page',
        body: '## Architecture\nA tidy design.',
      },
      {
        id: ID.graveyard,
        url: url(ID.graveyard),
        title: 'Graveyard',
        parentId: ID.hq,
        parentKind: 'page',
        body: `<page url="${url(ID.oldIdea)}">Old idea</page>`,
      },
      {
        id: ID.oldIdea,
        url: url(ID.oldIdea),
        title: 'Old idea',
        parentId: ID.graveyard,
        parentKind: 'page',
        body: '',
      },
      rowPage(ID.rowWidget, ID.projectsDb, 'Widget', 'Widget overview body.'),
      rowPage(ID.rowWidgetOld, ID.projectsDb, 'Widget (old record)'),
      rowPage(ID.rowGadget, ID.projectsDb, 'Gadget'),
      rowPage(ID.taskShip, ID.tasksDb, 'Widget: ship v1', 'Launch checklist lives here.'),
      rowPage(ID.taskDraft, ID.tasksDb, 'Widget: draft copy'),
      rowPage(ID.taskBlank, ID.tasksDb, ''),
      rowPage(ID.phaseTaskDraft, ID.phaseTasksDb, 'Draft copy'),
      rowPage(ID.phaseTaskLaunch, ID.phaseTasksDb, 'Launch'),
      rowPage(ID.eventJam, ID.eventsDb, 'Game Jam'),
      rowPage(ID.eventCup, ID.eventsDb, 'Code Cup'),
      rowPage(ID.decisionOne, ID.decisionsDb, 'Use a web app'),
      rowPage(ID.decisionTwo, ID.decisionsDb, 'Portfolio rule'),
    ],
    databases: [
      {
        id: ID.projectsDb,
        url: url(ID.projectsDb),
        title: 'Projects',
        parentId: ID.hq,
        dataSources: [
          {
            url: 'collection://p',
            name: 'Projects',
            schema: {
              Project: { name: 'Project', type: 'title' },
              Status: {
                name: 'Status',
                type: 'select',
                options: [{ name: 'Active' }, { name: 'Done' }, { name: 'Backlog' }],
              },
              Focus: { name: 'Focus', type: 'text' },
              Next: { name: 'Next', type: 'text' },
              Blocker: { name: 'Blocker', type: 'text' },
              Progress: { name: 'Progress', type: 'number' },
              Open: { name: 'Open', type: 'rollup' },
            },
            rows: [
              {
                url: url(ID.rowWidget),
                Project: 'Widget',
                Status: 'Active',
                Focus: 'Ship a small widget',
                Next: 'Write the launch post',
                Blocker: 'Waiting for the owner to pick a name',
                Progress: 0.5,
                Open: 'rollupResult://x/y',
              },
              {
                url: url(ID.rowWidgetOld),
                Project: 'Widget (old record)',
                Status: 'Done',
                Focus: 'Merged into Widget',
              },
              { url: url(ID.rowGadget), Project: 'Gadget', Status: 'Backlog' },
            ],
          },
        ],
      },
      {
        id: ID.tasksDb,
        url: url(ID.tasksDb),
        title: 'Tasks',
        parentId: ID.hq,
        dataSources: [
          {
            url: 'collection://t',
            name: 'Tasks',
            schema: {
              Task: { name: 'Task', type: 'title' },
              Project: { name: 'Project', type: 'relation' },
              Status: { name: 'Status', type: 'select' },
              Done: { name: 'Done', type: 'checkbox' },
              Priority: { name: 'Priority', type: 'select' },
              Notes: { name: 'Notes', type: 'text' },
              Created: { name: 'Created', type: 'created_time' },
            },
            rows: [
              {
                url: url(ID.taskShip),
                Task: 'Widget: ship v1',
                Project: JSON.stringify([url(ID.rowWidget)]),
                Status: 'In progress',
                Done: '__NO__',
                Priority: 'High',
                Notes: 'Deploy \\~ carefully',
                Created: '2026-01-01T08:00:00.000Z',
              },
              {
                url: url(ID.taskDraft),
                Task: 'Widget: draft copy',
                Project: JSON.stringify([url(ID.rowWidgetOld)]),
                Status: 'Done',
                Done: '__YES__',
                Priority: 'Low',
                Created: '2026-01-01T08:05:00.000Z',
              },
              { url: url(ID.taskBlank), Task: '', Done: '__NO__' },
            ],
          },
        ],
      },
      {
        id: ID.phaseTasksDb,
        url: url(ID.phaseTasksDb),
        title: 'Build & Tasks',
        parentId: ID.plan,
        dataSources: [
          {
            url: 'collection://pt',
            name: 'Build & Tasks',
            schema: {
              Task: { name: 'Task', type: 'title' },
              Phase: {
                name: 'Phase',
                type: 'select',
                options: [{ name: '0 Foundation' }, { name: '1 Build' }, { name: '9 Unused' }],
              },
              Status: { name: 'Status', type: 'select' },
              Due: { name: 'Due', type: 'date' },
            },
            rows: [
              {
                url: url(ID.phaseTaskDraft),
                Task: 'Draft copy',
                Phase: '0 Foundation',
                Status: 'To do',
                'date:Due:start': '2026-01-10',
                'date:Due:is_datetime': 0,
              },
              {
                url: url(ID.phaseTaskLaunch),
                Task: 'Launch',
                Phase: '1 Build',
                Status: 'To do',
                'date:Due:start': '2026-01-20',
                'date:Due:is_datetime': 0,
              },
            ],
          },
        ],
      },
      {
        id: ID.eventsDb,
        url: url(ID.eventsDb),
        title: 'Hackathons',
        parentId: ID.hq,
        dataSources: [
          {
            url: 'collection://h',
            name: 'Hackathons',
            schema: {
              Name: { name: 'Name', type: 'title' },
              Status: { name: 'Status', type: 'select' },
              Registration: { name: 'Registration', type: 'select' },
              Build: { name: 'Build', type: 'select' },
              Start: { name: 'Start', type: 'date' },
              End: { name: 'End', type: 'date' },
              Team: { name: 'Team', type: 'text' },
            },
            rows: [
              {
                url: url(ID.eventJam),
                Name: 'Game Jam',
                Status: 'Active',
                Registration: 'Registered',
                Build: 'Demo ready',
                'date:Start:start': '2026-02-01',
                'date:End:start': '2026-02-02',
                Team: 'Team A',
              },
              {
                url: url(ID.eventCup),
                Name: 'Code Cup',
                Status: 'Considering',
                'date:Start:start': '2026-03-05',
                'date:End:start': '2026-03-01',
              },
            ],
          },
        ],
      },
      {
        id: ID.decisionsDb,
        url: url(ID.decisionsDb),
        title: 'Decision Log',
        parentId: ID.hq,
        dataSources: [
          {
            url: 'collection://d',
            name: 'Decision Log',
            schema: {
              Decision: { name: 'Decision', type: 'title' },
              'Chosen Action': { name: 'Chosen Action', type: 'text' },
              Rationale: { name: 'Rationale', type: 'text' },
              Context: { name: 'Context', type: 'text' },
              Business: { name: 'Business', type: 'relation' },
              'Decision Date': { name: 'Decision Date', type: 'date' },
              'Made By': { name: 'Made By', type: 'select' },
              Created: { name: 'Created', type: 'created_time' },
            },
            rows: [
              {
                url: url(ID.decisionOne),
                Decision: 'Use a web app',
                'Chosen Action': 'Build it as a web app.',
                Rationale: 'Fastest to ship.',
                Context: 'Choosing a platform.',
                Business: JSON.stringify([url(ID.rowWidget)]),
                'date:Decision Date:start': '2026-01-02',
                'Made By': 'ASSISTANT',
                Created: '2026-01-02T07:30:00.000Z',
              },
              {
                url: url(ID.decisionTwo),
                Decision: 'Portfolio rule',
                'Chosen Action': 'Two builds at most.',
                Business: JSON.stringify([url(ID.rowWidget), url(ID.rowGadget)]),
                'Made By': 'USER',
                Created: '2026-01-02T08:00:00.000Z',
              },
            ],
          },
        ],
      },
      {
        id: ID.colorsDb,
        url: url(ID.colorsDb),
        title: 'Colours',
        parentId: ID.spec,
        dataSources: [
          {
            url: 'collection://c',
            name: 'Colours',
            schema: {
              Colour: { name: 'Colour', type: 'title' },
              Hex: { name: 'Hex', type: 'text' },
              Used: { name: 'Used', type: 'checkbox' },
              Weight: { name: 'Weight', type: 'number' },
              Tags: { name: 'Tags', type: 'multi_select' },
              Pair: { name: 'Pair', type: 'relation' },
              Task: { name: 'Task', type: 'relation' },
              Since: { name: 'Since', type: 'date' },
              Link: { name: 'Link', type: 'url' },
            },
            rows: [
              {
                url: url(ID.colorRed),
                Colour: 'Red',
                Hex: '#f00',
                Used: '__YES__',
                Weight: 3,
                Tags: JSON.stringify(['warm', 'bold']),
                Pair: JSON.stringify([url(ID.colorBlue)]),
                Task: JSON.stringify([url(ID.taskShip)]),
                'date:Since:start': '2026-01-01',
                'date:Since:end': '2026-01-31',
                Link: 'https://example.com/red',
              },
              { url: url(ID.colorBlue), Colour: 'Blue', Used: '__NO__' },
            ],
          },
        ],
      },
      {
        id: ID.viewOfTasks,
        url: url(ID.viewOfTasks),
        title: 'View of Tasks',
        parentId: ID.hq,
        linkedView: true,
        dataSources: [],
      },
    ],
  };
}

export function fixturePlan(): MigrationPlan {
  return {
    version: 1,
    projects: [
      {
        key: 'widget',
        name: 'Widget',
        slug: 'widget',
        kind: 'software',
        source: ID.rowWidget,
        legacy: [ID.rowWidgetOld],
        references: [ID.hq],
      },
      { key: 'gadget', name: 'Gadget', slug: 'gadget', kind: 'other', source: ID.rowGadget },
    ],
    databases: {
      [ID.projectsDb]: {
        role: 'projects',
        fields: { state: 'Status', objective: 'Focus', nextAction: 'Next' },
        states: { Active: 'active', Done: 'done', Backlog: 'planning' },
        items: [{ property: 'Blocker', kind: 'blocker' }],
      },
      [ID.tasksDb]: {
        role: 'tasks',
        projectProperty: 'Project',
        fields: {
          title: 'Task',
          status: 'Status',
          done: 'Done',
          priority: 'Priority',
          notes: ['Notes'],
        },
        statuses: { 'Not started': 'todo', 'In progress': 'doing', Done: 'done' },
        priorities: { High: 'high', Medium: 'normal', Low: 'low' },
      },
      [ID.phaseTasksDb]: {
        role: 'tasks',
        project: 'widget',
        fields: { title: 'Task', status: 'Status', due: 'Due', milestone: 'Phase' },
        statuses: { 'To do': 'todo', Done: 'done' },
        duplicates: { [ID.phaseTaskDraft]: ID.taskDraft },
      },
      [ID.eventsDb]: {
        role: 'hackathons',
        fields: {
          name: 'Name',
          status: 'Status',
          registration: 'Registration',
          build: 'Build',
          start: 'Start',
          end: 'End',
          team: 'Team',
        },
        statuses: { Active: 'active', Considering: 'considering' },
        registrations: { Registered: 'registered' },
        builds: { 'Demo ready': 'demo_ready' },
      },
      [ID.decisionsDb]: {
        role: 'decisions',
        relation: 'Business',
        relationProjects: { [ID.rowWidget]: 'widget', [ID.rowGadget]: 'gadget' },
        fields: {
          title: 'Decision',
          decision: ['Chosen Action', 'Rationale'],
          context: ['Context'],
          date: 'Decision Date',
          madeBy: 'Made By',
        },
        origins: { USER: 'owner', ASSISTANT: 'ai-client' },
        clients: { ASSISTANT: 'Assistant' },
      },
      [ID.colorsDb]: { role: 'table' },
    },
    placements: [
      { id: ID.hq, under: 'ideas/Acme' },
      { id: ID.plan, under: 'project:widget:planning' },
      { id: ID.spec, under: 'project:widget:architecture' },
      { id: ID.projectsDb, under: 'project:widget:tables' },
      { id: ID.graveyard, under: 'archive', archived: true },
      { id: ID.eventsDb, under: 'hackathons' },
    ],
    skip: [{ id: ID.taskBlank, reason: 'Blank row' }],
  };
}
