import { execFile } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { promisify } from 'node:util';
import type { GitStatus, SyncReport } from '../../src/db/companion/wire';
import type { Repositories } from '../../src/db/repositories';

export type { GitStatus, SyncReport };
import {
  buildWorkspaceFiles,
  GENERATED_MARK,
  HUMAN_FOLDERS,
  projectRoot,
} from '../../src/features/context/workspace';
import type { Project } from '../../src/types/domain';
import type { SqliteStore } from './sqlite/store';

const run = promisify(execFile);

/*
 * The live technical workspace (ADR-060). The companion keeps it in step
 * with canonical LOWTIDE state: after any change it regenerates the files it
 * owns (those carrying the "Generated by LOWTIDE" marker, plus .lowtide/),
 * rewriting only what changed and removing only its own stale files. Every
 * other file belongs to a person or an AI client and is never modified or
 * deleted. All paths are checked to stay inside the workspace, links included.
 */

export class PathError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PathError';
  }
}

export const MAX_READ_BYTES = 256 * 1024;

export const WORKSPACE_GITIGNORE = `# LOWTIDE technical workspace. Private life data never lives here, and the
# generator's bookkeeping in .lowtide/ is rebuilt on every sync.
.lowtide/
# Never commit databases, backups or secrets.
*.sqlite
*.sqlite-*
*.db
*.db-*
lowtide-backup*.json
.env
.env.*
*.pem
*.key
.DS_Store
`;

type Scope = { kind: 'project'; root: string } | { kind: 'workspace' };

const isGenerated = (text: string) => text.startsWith(GENERATED_MARK);
const bookkeeping = (path: string) => path.startsWith('.lowtide/') || path.includes('/.lowtide/');

export class WorkspaceSync {
  readonly root: string;
  private timer: ReturnType<typeof setTimeout> | undefined;
  private off: (() => void) | undefined;
  private running: Promise<SyncReport> | undefined;
  private stopped = false;
  private readonly listeners = new Set<(report: SyncReport) => void>();
  lastReport: SyncReport | undefined;

  constructor(
    private readonly store: SqliteStore,
    private readonly repositories: Repositories,
    dir: string,
    private readonly now: () => Date = () => new Date(),
    private readonly debounceMs = 250,
  ) {
    mkdirSync(dir, { recursive: true });
    this.root = realpathSync(dir);
  }

  /** Syncs now, then after every change (debounced). */
  async start(): Promise<SyncReport> {
    this.off = this.store.onChange(() => this.schedule());
    return this.sync();
  }

  /** Stops listening and waits for a sync already under way. */
  async stop() {
    this.off?.();
    if (this.timer) clearTimeout(this.timer);
    this.stopped = true;
    await this.running;
  }

  /** Hears about every completed sync. */
  onSynced(listener: (report: SyncReport) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private schedule() {
    if (this.stopped) return;
    if (this.timer) clearTimeout(this.timer);
    this.timer = setTimeout(() => void this.sync().catch(() => undefined), this.debounceMs);
  }

  /** Resolves a workspace-relative path, refusing anything outside the root (links included). */
  resolve(path: string, scope: Scope = { kind: 'workspace' }): string {
    if (path.includes('\0')) throw new PathError('Invalid path');
    const absolute = resolve(this.root, path);
    const rel = relative(this.root, absolute);
    if (rel === '' || rel.startsWith('..') || resolve(this.root, rel) !== absolute) {
      throw new PathError('Path is outside the workspace');
    }
    const normal = rel.split(sep).join('/');
    if (scope.kind === 'project' && !normal.startsWith(`${scope.root}/`)) {
      throw new PathError('Path is outside this connection’s project');
    }
    let probe = absolute;
    while (!existsSync(probe)) probe = dirname(probe);
    const real = realpathSync(probe);
    if (real !== this.root && !real.startsWith(this.root + sep)) {
      throw new PathError('Path leaves the workspace through a link');
    }
    return absolute;
  }

  read(path: string, scope: Scope = { kind: 'workspace' }): string {
    if (bookkeeping(path)) throw new PathError('LOWTIDE bookkeeping isn’t readable here');
    const file = this.resolve(path, scope);
    if (!existsSync(file) || !statSync(file).isFile()) throw new PathError(`No file ${path}`);
    if (statSync(file).size > MAX_READ_BYTES) throw new PathError(`${path} is too large`);
    return readFileSync(file, 'utf8');
  }

  /** Text files visible in a scope, workspace-relative and sorted (bookkeeping excluded). */
  list(scope: Scope = { kind: 'workspace' }): string[] {
    const out: string[] = [];
    const walk = (rel: string) => {
      const abs = this.resolve(rel);
      for (const name of readdirSync(abs)) {
        if (name === '.lowtide' || name === '.git') continue;
        const child = `${rel}/${name}`;
        let absolute: string;
        try {
          absolute = this.resolve(child);
        } catch {
          continue; // links out of the workspace are skipped, never followed
        }
        const stat = statSync(absolute);
        if (stat.isDirectory()) walk(child);
        else if (/\.(md|txt|json)$/.test(name) && stat.size <= MAX_READ_BYTES) out.push(child);
      }
    };
    const starts =
      scope.kind === 'project'
        ? [scope.root]
        : readdirSync(this.root).filter((n) => n !== '.lowtide' && n !== '.git');
    for (const start of starts) {
      const abs = join(this.root, start);
      if (!existsSync(abs)) continue;
      if (statSync(abs).isDirectory()) walk(start);
      else if (/\.(md|txt|json)$/.test(start)) out.push(start);
    }
    return out.sort();
  }

  /** People's own documents per project (for CONTEXT.md "Important documents"). */
  humanDocuments(projects: readonly Project[]): Record<string, string[]> {
    const out: Record<string, string[]> = {};
    for (const project of projects) {
      const root = projectRoot(project);
      if (!existsSync(join(this.root, root))) continue;
      out[project.id] = this.list({ kind: 'project', root })
        .filter((p) => !p.endsWith('.gitkeep'))
        .filter((p) => {
          try {
            return !isGenerated(this.read(p));
          } catch {
            return false;
          }
        })
        .slice(0, 20);
    }
    return out;
  }

  /** Regenerates the files LOWTIDE owns. Never touches anything else. */
  sync(): Promise<SyncReport> {
    const previous = this.running ?? Promise.resolve(undefined);
    const next = previous.then(() => this.syncNow());
    this.running = next.catch(() => undefined) as Promise<SyncReport>;
    return next;
  }

  private async syncNow(): Promise<SyncReport> {
    const now = this.now();
    const data = (await this.repositories.backup.exportBackup()).data;
    const { generated, folders } = buildWorkspaceFiles(data, now, {
      documents: this.humanDocuments(data.projects),
    });
    const report: SyncReport = {
      written: [],
      removed: [],
      unchanged: 0,
      conflicts: [],
      at: now.toISOString(),
    };

    for (const folder of folders) {
      const abs = this.resolve(folder);
      if (!existsSync(abs)) mkdirSync(abs, { recursive: true });
      if (readdirSync(abs).length === 0) writeFileSync(join(abs, '.gitkeep'), '');
    }

    for (const [path, content] of generated) {
      const abs = this.resolve(path);
      if (existsSync(abs)) {
        const current = readFileSync(abs, 'utf8');
        if (current === content) {
          report.unchanged += 1;
          continue;
        }
        if (!bookkeeping(path) && !isGenerated(current)) {
          report.conflicts.push(path);
          continue;
        }
      }
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content);
      report.written.push(path);
    }

    const ledger = join(this.root, '.lowtide', 'generated.json');
    const before: string[] = existsSync(ledger)
      ? (JSON.parse(readFileSync(ledger, 'utf8')) as string[])
      : [];
    for (const path of before) {
      if (generated.has(path)) continue;
      const abs = this.resolve(path);
      if (!existsSync(abs)) continue;
      if (bookkeeping(path) || isGenerated(readFileSync(abs, 'utf8'))) {
        rmSync(abs);
        report.removed.push(path);
      }
    }
    mkdirSync(dirname(ledger), { recursive: true });
    writeFileSync(ledger, `${JSON.stringify([...generated.keys()], null, 2)}\n`);
    this.lastReport = report;
    for (const listener of [...this.listeners]) {
      try {
        listener(report);
      } catch {
        // A listener never affects the workspace.
      }
    }
    return report;
  }

  /** Makes the workspace its own private Git repository. Never adds a remote or commits. */
  async gitInit(): Promise<GitStatus> {
    if (!existsSync(join(this.root, '.git'))) {
      await run('git', ['init', '-b', 'main'], { cwd: this.root, timeout: 15_000, env: gitEnv() });
    }
    const ignore = join(this.root, '.gitignore');
    if (!existsSync(ignore)) writeFileSync(ignore, WORKSPACE_GITIGNORE);
    return this.gitStatus();
  }

  async gitStatus(): Promise<GitStatus> {
    if (!existsSync(join(this.root, '.git'))) return { repository: false, remotes: [], changes: 0 };
    const opts = { cwd: this.root, timeout: 15_000, env: gitEnv() };
    const remotes = (await run('git', ['remote'], opts)).stdout.split('\n').filter(Boolean);
    const changes = (await run('git', ['status', '--porcelain'], opts)).stdout
      .split('\n')
      .filter(Boolean).length;
    return { repository: true, remotes, changes };
  }
}

function gitEnv() {
  return { ...process.env, GIT_TERMINAL_PROMPT: '0' };
}

export { HUMAN_FOLDERS };
