import type { BackupData } from '../../db/repositories';
import { formatDuration } from '../../lib/duration';
import { toLocalDate } from '../../lib/time';
import type { LedgerEvent, Project } from '../../types/domain';
import { PRIVATE_EVENT_TYPES } from '../../types/domain';
import { hackathonStages, STAGE_LABEL } from '../hackathons/progress';
import { slugOf } from './slug';
import { LANE_LABEL, STATE_LABEL, summariseProject } from '../projects/summary';
import { activeMinutes } from '../work/duration';
import { buildContextPack, renderContextMarkdown } from './pack';

/*
 * The technical workspace (ADR-044, ADR-054): a folder of human-readable files
 * an AI coding client (or you) can read, generated from LOWTIDE's records.
 *
 *   README.md                    index and privacy note
 *   projects/<slug>/PROJECT.md   objective, state, milestones, board
 *   projects/<slug>/CONTEXT.md   the PROJECT-scope context pack
 *   projects/<slug>/decisions/   one file per decision
 *   projects/<slug>/ai/sessions/ one file per reported AI session
 *   projects/<slug>/{planning,research,docs,files,assets,ai/handoffs,ai/summaries,archive}/
 *   projects/<slug>/.lowtide/summary.json   structured data for the companion
 *   hackathons/<slug>.md         technical sheet per hackathon
 *   daily/YYYY-MM.md             project work sessions per day (technical only)
 *   inbox/, archive/             kept empty: raw inbox is never exported
 *   .lowtide/manifest.json       what was generated, for the companion
 *
 * Never written: protected time, sleep and off-time logs, routines and habit
 * entries (including medication), health-type records, raw inbox contents,
 * college items. There is no option to include protected time.
 */

export const GENERATED = (at: string) =>
  `<!-- Generated by LOWTIDE ${at}. Edits here are overwritten on the next export. -->`;

const KEEP = '';

export interface ProjectSummaryJson {
  id: string;
  slug: string;
  name: string;
  state: string;
  phase?: string;
  objective?: string;
  nextAction?: string;
  completionPercent: number | null;
  lanes: Record<string, { title: string; waitingOn?: string }[]>;
  recentActivity: { at: string; type: string; title?: string }[];
  minutesThisWeek: number;
}

export function buildWorkspace(data: BackupData, now: Date): Map<string, string> {
  const at = now.toISOString();
  const today = toLocalDate(now);
  const files = new Map<string, string>();
  const titles = new Map<string, string>();
  for (const t of data.tasks) titles.set(t.id, t.title);
  for (const m of data.milestones) titles.set(m.id, m.title);
  for (const i of data.projectItems) titles.set(i.id, i.title);
  for (const d of data.decisions) titles.set(d.id, d.title);

  const live = (p: Project) => p.state !== 'done' && p.state !== 'archived';
  const manifest: { slug: string; id: string; name: string; archived: boolean }[] = [];

  for (const project of data.projects) {
    const root =
      live(project) || project.state === 'done'
        ? `projects/${project.slug}`
        : `archive/projects/${project.slug}`;
    manifest.push({
      slug: project.slug,
      id: project.id,
      name: project.name,
      archived: project.state === 'archived',
    });
    const s = summariseProject(
      project,
      data.milestones,
      data.projectItems,
      data.tasks,
      data.workSessions,
      today,
    );

    files.set(`${root}/PROJECT.md`, projectMarkdown(project, s, at));
    files.set(
      `${root}/CONTEXT.md`,
      renderContextMarkdown(
        buildContextPack(data, { kind: 'project', projectId: project.id }, now),
      ),
    );

    const decisions = data.decisions
      .filter((d) => d.projectId === project.id)
      .sort((a, b) => a.decidedAt.localeCompare(b.decidedAt));
    const superseded = new Set(decisions.map((d) => d.supersedesId).filter(Boolean));
    decisions.forEach((d, i) => {
      const n = String(i + 1).padStart(4, '0');
      files.set(
        `${root}/decisions/${n}-${slugOf(d.title)}.md`,
        [
          GENERATED(at),
          `# ${n}. ${d.title}`,
          '',
          `- Date: ${d.decidedAt.slice(0, 10)}`,
          `- Status: ${superseded.has(d.id) ? 'Superseded' : 'Accepted'}`,
          ...(d.supersedesId
            ? [`- Supersedes: ${titles.get(d.supersedesId) ?? d.supersedesId}`]
            : []),
          ...(d.origin === 'accepted-proposal'
            ? ['- Proposed by an AI client, accepted by the owner']
            : []),
          '',
          ...(d.context ? ['## Context', '', d.context, ''] : []),
          '## Decision',
          '',
          d.decision,
          '',
          ...(d.consequences ? ['## Consequences', '', d.consequences, ''] : []),
        ].join('\n'),
      );
    });

    for (const session of data.aiSessions.filter((a) => a.projectId === project.id)) {
      files.set(
        `${root}/ai/sessions/${session.startedAt.slice(0, 10)}-${slugOf(session.client)}-${session.id.slice(0, 8)}.md`,
        [
          GENERATED(at),
          `# AI session: ${session.client}`,
          '',
          `- Started: ${session.startedAt}`,
          `- Ended: ${session.endedAt}`,
          `- Scope: ${session.scope}`,
          '',
          session.summary,
          '',
          ...(session.filesTouched?.length
            ? ['## Files touched', '', ...session.filesTouched.map((f) => `- ${f}`), '']
            : []),
        ].join('\n'),
      );
    }

    for (const dir of [
      'planning',
      'research',
      'docs',
      'files',
      'assets',
      'ai/handoffs',
      'ai/summaries',
      'archive',
    ]) {
      files.set(`${root}/${dir}/.gitkeep`, KEEP);
    }

    const events = data.events
      .filter((e) => e.projectId === project.id && !PRIVATE_EVENT_TYPES.includes(e.type))
      .sort((a, b) => b.at.localeCompare(a.at))
      .slice(0, 20);
    const summaryJson: ProjectSummaryJson = {
      id: project.id,
      slug: project.slug,
      name: project.name,
      state: project.state,
      ...(project.phase ? { phase: project.phase } : {}),
      ...(project.objective ? { objective: project.objective } : {}),
      ...(project.nextAction ? { nextAction: project.nextAction } : {}),
      completionPercent: s.completion?.percent ?? null,
      lanes: Object.fromEntries(
        Object.entries(s.lanes).map(([lane, entries]) => [
          lane,
          entries.map((e) => ({ title: e.title, ...(e.detail ? { waitingOn: e.detail } : {}) })),
        ]),
      ),
      recentActivity: events.map((e: LedgerEvent) => ({
        at: e.at,
        type: e.type,
        ...(titles.has(e.entityId) ? { title: titles.get(e.entityId)! } : {}),
      })),
      minutesThisWeek: s.minutesThisWeek,
    };
    files.set(`${root}/.lowtide/summary.json`, `${JSON.stringify(summaryJson, null, 2)}\n`);
  }

  for (const h of data.hackathons) {
    const stages = hackathonStages(h);
    files.set(
      `hackathons/${slugOf(h.name)}-${h.id.slice(0, 8)}.md`,
      [
        GENERATED(at),
        `# ${h.name}`,
        '',
        `- Status: ${h.status}`,
        ...(h.registrationDeadline ? [`- Registration deadline: ${h.registrationDeadline}`] : []),
        ...(h.eventStart
          ? [`- Event: ${h.eventStart}${h.eventEnd ? ` to ${h.eventEnd}` : ''}`]
          : []),
        ...(h.team ? [`- Team: ${h.team}`] : []),
        ...(h.nextAction ? [`- Next action: ${h.nextAction}`] : []),
        '',
        '## Stages',
        '',
        ...stages.map(
          (st) =>
            `- [${st.state === 'done' ? 'x' : st.state === 'active' ? '>' : ' '}] ${STAGE_LABEL[st.key]}`,
        ),
        '',
        ...(h.problemStatement ? ['## Problem statement', '', h.problemStatement, ''] : []),
      ].join('\n'),
    );
  }

  // Technical daily log: project and task work only (no general/college work, no life logs).
  const byMonth = new Map<string, Map<string, string[]>>();
  const names = new Map(data.projects.map((p) => [p.id, p.name]));
  for (const w of [...data.workSessions].sort((a, b) => a.startedAt.localeCompare(b.startedAt))) {
    if (!w.endedAt || !w.projectId || (w.kind !== 'project' && w.kind !== 'task')) continue;
    const month = w.localDate.slice(0, 7);
    const days = byMonth.get(month) ?? new Map<string, string[]>();
    byMonth.set(month, days);
    const lines = days.get(w.localDate) ?? [];
    days.set(w.localDate, lines);
    lines.push(
      `- ${names.get(w.projectId) ?? 'Project'}: ${formatDuration(activeMinutes(w))}${w.intent ? `, ${w.intent}` : ''}${w.outcome ? ` → ${w.outcome}` : ''}`,
    );
  }
  for (const [month, days] of byMonth) {
    files.set(
      `daily/${month}.md`,
      [
        GENERATED(at),
        `# Project work, ${month}`,
        '',
        ...[...days].flatMap(([day, lines]) => [`## ${day}`, '', ...lines, '']),
      ].join('\n'),
    );
  }

  files.set('inbox/.gitkeep', KEEP);
  files.set('archive/.gitkeep', KEEP);
  files.set(
    'README.md',
    [
      GENERATED(at),
      '# LOWTIDE workspace',
      '',
      'Technical project knowledge exported from LOWTIDE. Open a project’s CONTEXT.md first.',
      '',
      '## Projects',
      '',
      ...(data.projects.length
        ? data.projects.map(
            (p) =>
              `- [${p.name}](${live(p) || p.state === 'done' ? '' : 'archive/'}projects/${p.slug}/PROJECT.md) (${STATE_LABEL[p.state]})`,
          )
        : ['None yet.']),
      '',
      '## Privacy',
      '',
      'This folder never contains protected time, sleep or off-time logs, routines or',
      'habit logs (including medication), health-type records, college records or raw',
      'inbox thoughts. Those stay in LOWTIDE’s private storage on this device.',
      'Files marked "Generated by LOWTIDE" are replaced on the next export; anything',
      'else you or an AI client add here is left alone.',
      '',
    ].join('\n'),
  );
  files.set(
    '.lowtide/manifest.json',
    `${JSON.stringify({ format: 'lowtide-workspace', version: 1, generatedAt: at, projects: manifest }, null, 2)}\n`,
  );
  return new Map([...files].sort(([a], [b]) => a.localeCompare(b)));
}

function projectMarkdown(
  project: Project,
  s: ReturnType<typeof summariseProject>,
  at: string,
): string {
  const lanes = (Object.keys(s.lanes) as (keyof typeof s.lanes)[]).flatMap((lane) =>
    s.lanes[lane].length
      ? [
          `### ${LANE_LABEL[lane]}`,
          '',
          ...s.lanes[lane].map((e) => `- ${e.title}${e.detail ? ` (waiting on ${e.detail})` : ''}`),
          '',
        ]
      : [],
  );
  return [
    GENERATED(at),
    `# ${project.name}`,
    '',
    `- State: ${STATE_LABEL[project.state]}`,
    ...(project.phase ? [`- Phase: ${project.phase}`] : []),
    ...(project.objective ? [`- Objective: ${project.objective}`] : []),
    ...(project.nextAction ? [`- Next action: ${project.nextAction}`] : []),
    ...(project.repoUrl ? [`- Repository: ${project.repoUrl}`] : []),
    `- Completion: ${s.completion ? `${s.completion.percent}% of milestone weight` : 'no milestones yet'}`,
    '',
    '## Milestones',
    '',
    ...(s.milestones.length
      ? s.milestones.map(
          (m) =>
            `- [${m.completedAt ? 'x' : ' '}] ${m.title}${m.weight !== 1 ? ` (weight ${m.weight})` : ''}${m.dueOn ? `, due ${m.dueOn}` : ''}`,
        )
      : ['None yet.']),
    '',
    '## Board',
    '',
    ...(lanes.length ? lanes : ['Empty.', '']),
  ].join('\n');
}
