import type { BackupData } from '../../db/repositories';
import { toLocalDate } from '../../lib/time';
import type { LedgerEvent, Project } from '../../types/domain';
import { PRIVATE_EVENT_TYPES } from '../../types/domain';
import { hackathonStages, STAGE_LABEL } from '../hackathons/progress';
import { LANE_LABEL, STATE_LABEL, summariseProject } from '../projects/summary';
import { buildContextPack, notePath, renderContextMarkdown, type ContextOptions } from './pack';
import { slugOf } from './slug';
import { projectSpaceFiles } from './space-files';

/*
 * The technical workspace (ADR-044, ADR-060): human-readable files an AI
 * coding client (or you) can read, generated from LOWTIDE's records.
 *
 *   README.md                              index and privacy note
 *   projects/<slug>/PROJECT.md             objective, state, milestones, board
 *   projects/<slug>/CONTEXT.md             the PROJECT-scope context pack
 *   projects/<slug>/decisions/NNNN-*.md    the decision log
 *   projects/<slug>/ai/sessions/*.md       reported AI sessions
 *   projects/<slug>/docs/notes/*.md        notes      ┐
 *   projects/<slug>/ai/handoffs/*.md       handoffs   │ projected from LOWTIDE's
 *   projects/<slug>/ai/summaries/*.md      summaries  │ notes (canonical there)
 *   projects/<slug>/research/*.md          research   ┘
 *   projects/<slug>/space/**.md            the project's SPACE pages and tables
 *   projects/<slug>/{planning,docs,files,assets,archive}/   yours: never touched
 *   hackathons/<slug>-<id>.md              technical sheet per hackathon
 *   shared/                                yours: cross-project documents
 *   archive/projects/<slug>/               archived projects
 *   .lowtide/                              generator bookkeeping
 *
 * Every generated file starts with the GENERATED marker and is rewritten
 * from records; nobody edits PROJECT.md or CONTEXT.md by hand. Any file
 * without the marker belongs to a person and is never modified or removed.
 *
 * Never written: protected time, sleep and off-time logs, routines and habit
 * entries (including medication), health-type records, raw inbox contents,
 * college items. There is no option to include protected time.
 */

export const GENERATED_MARK = '<!-- Generated by LOWTIDE';
/**
 * The first line of every generated Markdown file. No timestamp: a file only
 * changes when what it describes changes (quiet diffs in a Git workspace).
 */
export const GENERATED_LINE = `${GENERATED_MARK}. Edit it in LOWTIDE; changes here are overwritten. -->`;

/** Folders kept for people and AI clients to fill; LOWTIDE only makes sure they exist. */
export const HUMAN_FOLDERS = ['planning', 'research', 'docs', 'files', 'assets', 'archive'];

export interface ProjectSummaryJson {
  id: string;
  slug: string;
  name: string;
  state: string;
  phase?: string;
  objective?: string;
  nextAction?: string;
  completionPercent: number | null;
  lanes: Record<string, { title: string; waitingOn?: string }[]>;
  recentActivity: { at: string; type: string; title?: string }[];
  minutesThisWeek: number;
}

export interface WorkspaceFiles {
  /** Generated files: path → content. */
  generated: Map<string, string>;
  /** Folders that should exist (created empty, with a .gitkeep, if missing). */
  folders: string[];
}

export function projectRoot(project: Project): string {
  return project.state === 'archived'
    ? `archive/projects/${project.slug}`
    : `projects/${project.slug}`;
}

function titleMap(data: BackupData): Map<string, string> {
  const titles = new Map<string, string>();
  for (const t of data.tasks) titles.set(t.id, t.title);
  for (const m of data.milestones) titles.set(m.id, m.title);
  for (const i of data.projectItems) titles.set(i.id, i.title);
  for (const d of data.decisions) titles.set(d.id, d.title);
  for (const n of data.notes) titles.set(n.id, n.title);
  return titles;
}

/** A project's machine-readable summary (.lowtide/summary.json and the MCP summary tool). */
export function projectSummaryJson(
  data: BackupData,
  project: Project,
  now: Date,
  titles: Map<string, string> = titleMap(data),
): ProjectSummaryJson {
  const s = summariseProject(
    project,
    data.milestones,
    data.projectItems,
    data.tasks,
    data.workSessions,
    toLocalDate(now),
  );
  const events = data.events
    .filter((e) => e.projectId === project.id && !PRIVATE_EVENT_TYPES.includes(e.type))
    .sort((a, b) => b.at.localeCompare(a.at))
    .slice(0, 20);
  return {
    id: project.id,
    slug: project.slug,
    name: project.name,
    state: project.state,
    ...(project.phase ? { phase: project.phase } : {}),
    ...(project.objective ? { objective: project.objective } : {}),
    ...(project.nextAction ? { nextAction: project.nextAction } : {}),
    completionPercent: s.completion?.percent ?? null,
    lanes: Object.fromEntries(
      Object.entries(s.lanes).map(([lane, entries]) => [
        lane,
        entries.map((e) => ({ title: e.title, ...(e.detail ? { waitingOn: e.detail } : {}) })),
      ]),
    ),
    recentActivity: events.map((e: LedgerEvent) => ({
      at: e.at,
      type: e.type,
      ...(titles.has(e.entityId) ? { title: titles.get(e.entityId)! } : {}),
    })),
    minutesThisWeek: s.minutesThisWeek,
  };
}

/** The generated workspace, from one consistent snapshot. Deterministic for the same input. */
export function buildWorkspaceFiles(
  data: BackupData,
  now: Date,
  options: ContextOptions = {},
): WorkspaceFiles {
  const at = now.toISOString();
  const today = toLocalDate(now);
  const generated = new Map<string, string>();
  const folders = ['projects', 'hackathons', 'shared', 'archive'];
  const titles = titleMap(data);

  const manifest: { slug: string; id: string; name: string; archived: boolean; root: string }[] =
    [];

  for (const project of data.projects) {
    const root = projectRoot(project);
    manifest.push({
      slug: project.slug,
      id: project.id,
      name: project.name,
      archived: project.state === 'archived',
      root,
    });
    for (const folder of [
      ...HUMAN_FOLDERS,
      'decisions',
      'ai/handoffs',
      'ai/summaries',
      'ai/sessions',
    ]) {
      folders.push(`${root}/${folder}`);
    }
    const s = summariseProject(
      project,
      data.milestones,
      data.projectItems,
      data.tasks,
      data.workSessions,
      today,
    );
    generated.set(`${root}/PROJECT.md`, projectMarkdown(project, s));
    const space = projectSpaceFiles(data, project, root, GENERATED_LINE);
    for (const [path, content] of space) generated.set(path, content);
    const documents = {
      ...options.documents,
      [project.id]: [...(options.documents?.[project.id] ?? []), ...space.keys()].slice(0, 40),
    };
    generated.set(
      `${root}/CONTEXT.md`,
      renderContextMarkdown(
        buildContextPack(data, { kind: 'project', projectId: project.id }, now, {
          ...options,
          documents,
        }),
      ),
    );

    const decisions = data.decisions
      .filter((d) => d.projectId === project.id)
      .sort((a, b) => a.decidedAt.localeCompare(b.decidedAt) || a.id.localeCompare(b.id));
    const superseded = new Set(decisions.map((d) => d.supersedesId).filter(Boolean));
    decisions.forEach((d, i) => {
      const n = String(i + 1).padStart(4, '0');
      generated.set(
        `${root}/decisions/${n}-${slugOf(d.title)}.md`,
        [
          GENERATED_LINE,
          `# ${n}. ${d.title}`,
          '',
          `- Date: ${d.decidedAt.slice(0, 10)}`,
          `- Status: ${superseded.has(d.id) ? 'Superseded' : 'Accepted'}`,
          ...(d.supersedesId
            ? [`- Supersedes: ${titles.get(d.supersedesId) ?? d.supersedesId}`]
            : []),
          ...(d.origin === 'accepted-proposal'
            ? ['- Proposed by an AI client, accepted by the owner']
            : d.origin === 'ai-client'
              ? [`- Recorded by ${d.client ?? 'an AI client'}`]
              : []),
          '',
          ...(d.context ? ['## Context', '', d.context, ''] : []),
          '## Decision',
          '',
          d.decision,
          '',
          ...(d.consequences ? ['## Consequences', '', d.consequences, ''] : []),
        ].join('\n'),
      );
    });

    for (const session of data.aiSessions.filter((a) => a.projectId === project.id)) {
      generated.set(
        `${root}/ai/sessions/${session.startedAt.slice(0, 10)}-${slugOf(session.client)}-${session.id.slice(0, 8)}.md`,
        [
          GENERATED_LINE,
          `# AI session: ${session.client}`,
          '',
          `- Started: ${session.startedAt}`,
          `- Ended: ${session.endedAt}`,
          `- Scope: ${session.scope}`,
          ...(session.taskId ? [`- Task: ${titles.get(session.taskId) ?? session.taskId}`] : []),
          '',
          session.summary,
          '',
          ...(session.result ? ['## Result', '', session.result, ''] : []),
          ...(session.nextAction ? ['## Next action', '', session.nextAction, ''] : []),
          ...(session.filesTouched?.length
            ? ['## Files touched', '', ...session.filesTouched.map((f) => `- ${f}`), '']
            : []),
          ...(session.commits?.length
            ? ['## Commits', '', ...session.commits.map((c) => `- ${c}`), '']
            : []),
          ...(session.handoff ? ['## Handoff', '', session.handoff, ''] : []),
        ].join('\n'),
      );
    }

    for (const note of data.notes.filter((n) => n.projectId === project.id)) {
      const path = notePath(project.slug, note).replace(`projects/${project.slug}`, root);
      generated.set(
        path,
        [
          GENERATED_LINE,
          `# ${note.title}`,
          '',
          `- ${note.kind === 'note' ? 'Note' : note.kind === 'handoff' ? 'Handoff' : note.kind === 'summary' ? 'Summary' : 'Research'} by ${note.author === 'ai-client' ? (note.client ?? 'an AI client') : 'the owner'}, ${note.createdAt.slice(0, 10)}`,
          '',
          note.body,
          '',
        ].join('\n'),
      );
    }

    generated.set(
      `${root}/.lowtide/summary.json`,
      `${JSON.stringify(projectSummaryJson(data, project, now, titles), null, 2)}\n`,
    );
  }

  for (const h of data.hackathons) {
    const stages = hackathonStages(h);
    generated.set(
      `hackathons/${slugOf(h.name)}-${h.id.slice(0, 8)}.md`,
      [
        GENERATED_LINE,
        `# ${h.name}`,
        '',
        `- Status: ${h.status}`,
        ...(h.registrationDeadline ? [`- Registration deadline: ${h.registrationDeadline}`] : []),
        ...(h.eventStart
          ? [`- Event: ${h.eventStart}${h.eventEnd ? ` to ${h.eventEnd}` : ''}`]
          : []),
        ...(h.team ? [`- Team: ${h.team}`] : []),
        ...(h.nextAction ? [`- Next action: ${h.nextAction}`] : []),
        '',
        '## Stages',
        '',
        ...stages.map(
          (st) =>
            `- [${st.state === 'done' ? 'x' : st.state === 'active' ? '>' : ' '}] ${STAGE_LABEL[st.key]}`,
        ),
        '',
        ...(h.problemStatement ? ['## Problem statement', '', h.problemStatement, ''] : []),
      ].join('\n'),
    );
  }

  const live = (p: Project) => p.state !== 'archived';
  generated.set(
    'README.md',
    [
      GENERATED_LINE,
      '# LOWTIDE workspace',
      '',
      'Technical project knowledge from LOWTIDE. Open a project’s CONTEXT.md first.',
      '',
      '## Projects',
      '',
      ...(data.projects.length
        ? data.projects.map(
            (p) =>
              `- [${p.name}](${projectRoot(p)}/PROJECT.md) (${STATE_LABEL[p.state]}${live(p) ? '' : ', archived'})`,
          )
        : ['None yet.']),
      '',
      '## Who writes what',
      '',
      '- Files that start with "Generated by LOWTIDE" are rebuilt from LOWTIDE and',
      '  replaced whenever LOWTIDE changes. Edit them in LOWTIDE, not here.',
      '- Everything else is yours (and your AI clients’): planning/, docs/, files/,',
      '  assets/, archive/, research/ and shared/. LOWTIDE never changes or deletes it.',
      '',
      '## Privacy',
      '',
      'This folder never contains protected time, sleep or off-time logs, routines or',
      'habit logs (including medication), health-type records, college records or raw',
      'inbox thoughts. Those stay in LOWTIDE’s private storage.',
      '',
    ].join('\n'),
  );
  generated.set(
    '.lowtide/manifest.json',
    `${JSON.stringify({ format: 'lowtide-workspace', version: 2, generatedAt: at, projects: manifest }, null, 2)}\n`,
  );
  return {
    generated: new Map([...generated].sort(([a], [b]) => a.localeCompare(b))),
    folders: [...new Set(folders)].sort(),
  };
}

/**
 * The workspace as one flat file map (for the ZIP export in browser mode):
 * generated files plus a .gitkeep in each empty folder.
 */
export function buildWorkspace(
  data: BackupData,
  now: Date,
  options: ContextOptions = {},
): Map<string, string> {
  const { generated, folders } = buildWorkspaceFiles(data, now, options);
  const files = new Map(generated);
  for (const folder of folders) {
    if (![...generated.keys()].some((p) => p.startsWith(`${folder}/`))) {
      files.set(`${folder}/.gitkeep`, '');
    }
  }
  return new Map([...files].sort(([a], [b]) => a.localeCompare(b)));
}

function projectMarkdown(project: Project, s: ReturnType<typeof summariseProject>): string {
  const lanes = (Object.keys(s.lanes) as (keyof typeof s.lanes)[]).flatMap((lane) =>
    s.lanes[lane].length
      ? [
          `### ${LANE_LABEL[lane]}`,
          '',
          ...s.lanes[lane].map((e) => `- ${e.title}${e.detail ? ` (waiting on ${e.detail})` : ''}`),
          '',
        ]
      : [],
  );
  return [
    GENERATED_LINE,
    `# ${project.name}`,
    '',
    `- State: ${STATE_LABEL[project.state]}`,
    ...(project.phase ? [`- Phase: ${project.phase}`] : []),
    ...(project.objective ? [`- Objective: ${project.objective}`] : []),
    ...(project.nextAction ? [`- Next action: ${project.nextAction}`] : []),
    ...(project.repoUrl ? [`- Repository: ${project.repoUrl}`] : []),
    `- Completion: ${s.completion ? `${s.completion.percent}% of milestone weight` : 'no milestones yet'}`,
    '',
    '## Milestones',
    '',
    ...(s.milestones.length
      ? s.milestones.map(
          (m) =>
            `- [${m.completedAt ? 'x' : ' '}] ${m.title}${m.weight !== 1 ? ` (weight ${m.weight})` : ''}${m.dueOn ? `, due ${m.dueOn}` : ''}`,
        )
      : ['None yet.']),
    '',
    '## Board',
    '',
    ...(lanes.length ? lanes : ['Empty.', '']),
  ].join('\n');
}
